### ISSUE TITLE
Demo app won't launch

### ISSUE THREAD

**Issue by edward-jazzhands** [lnqs/textual-image#48]
Hey so the demo app won't launch for me. Someone else on the Discord group said they're getting the exact same error. Here is my traceback

```
python -m textual_image textual
Traceback (most recent call last):
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/_terminal.py", line 64, in get_cell_size
    with capture_terminal_response("\x1b[", "t", 0.1) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/_terminal.py", line 117, in capture_terminal_response
    response.sequence += read(stdin, 1, timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/_posix.py", line 34, in read
    raise TimeoutError("Timeout waiting for data")
TimeoutError: Timeout waiting for data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/__main__.py", line 28, in <module>
    from textual_image.demo.widget import run as run_textual_demo
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/demo/widget.py", line 18, in <module>
    from textual_image.widget import HalfcellImage, SixelImage, TGPImage, UnicodeImage
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/widget/__init__.py", line 16, in <module>
    get_cell_size()
  File "/home/brent/vscode-projects/TextualDon/.venv/lib/python3.12/site-packages/textual_image/_terminal.py", line 71, in get_cell_size
    raise TerminalError("Failed to get cell size") from e
textual_image._terminal.TerminalError: Failed to get cell size
```

**Comment by Taeivas** [comment]
I can confirm to have the same issue, running Windows 10 (64-bit) with Windows Terminal.

**Comment by j4james** [comment]
The cell size query is currently only supported in the preview version of Windows Terminal, so if you're using the stable version it's not expected to work yet (Sixel images are also only supported in the preview version).

**Comment by Taeivas** [comment]
Can confirm that I got it working in the Preview.

**Comment by lnqs** [comment]
Thanks for pointing that out. I guess we can close this issue then.
